[scripts/manifest] Retry on "fatal: unable to access" errors
I was hitting them constantly and thus was unable to have a full run of the script. It always terminated for one of the hundreds of repos. This retry fixed it.

```
Traceback (most recent call last):
  File "/home/build/scripts/manifest", line 196, in <module>
    remove_groups = config.get('platform',{}).get('remove_groups',[]),
  File "/home/build/scripts/manifest", line 40, in __init__
    self._lock()
  File "/home/build/scripts/manifest", line 145, in _lock
    remote_refs = self._lsremote(project_repo_url)
  File "/home/build/scripts/manifest", line 152, in _lsremote
    for ref in g.ls_remote(url).split('\n'):
  File "/usr/lib/python3/dist-packages/git/cmd.py", line 548, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/git/cmd.py", line 1014, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/lib/python3/dist-packages/git/cmd.py", line 825, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git ls-remote https://android.googlesource.com/platform/external/antlr.git
  stderr: 'fatal: unable to access 'https://android.googlesource.com/platform/external/antlr.git/': The requested URL returned error: 500'
```